export type CountryCode = {
  code: string;
  country: string;
  flag: string;
  countryPt: string;
};

export const countryCodes: CountryCode[] = [
  { code: "+351", country: "Portugal", flag: "🇵🇹", countryPt: "Portugal" },
  { code: "+1", country: "United States", flag: "🇺🇸", countryPt: "Estados Unidos" },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧", countryPt: "Reino Unido" },
  { code: "+34", country: "Spain", flag: "🇪🇸", countryPt: "Espanha" },
  { code: "+33", country: "France", flag: "🇫🇷", countryPt: "França" },
  { code: "+49", country: "Germany", flag: "🇩🇪", countryPt: "Alemanha" },
  { code: "+39", country: "Italy", flag: "🇮🇹", countryPt: "Itália" },
  { code: "+41", country: "Switzerland", flag: "🇨🇭", countryPt: "Suíça" },
  { code: "+32", country: "Belgium", flag: "🇧🇪", countryPt: "Bélgica" },
  { code: "+31", country: "Netherlands", flag: "🇳🇱", countryPt: "Holanda" },
  { code: "+352", country: "Luxembourg", flag: "🇱🇺", countryPt: "Luxemburgo" },
  { code: "+353", country: "Ireland", flag: "🇮🇪", countryPt: "Irlanda" },
  { code: "+43", country: "Austria", flag: "🇦🇹", countryPt: "Áustria" },
  { code: "+45", country: "Denmark", flag: "🇩🇰", countryPt: "Dinamarca" },
  { code: "+46", country: "Sweden", flag: "🇸🇪", countryPt: "Suécia" },
  { code: "+47", country: "Norway", flag: "🇳🇴", countryPt: "Noruega" },
  { code: "+358", country: "Finland", flag: "🇫🇮", countryPt: "Finlândia" },
  { code: "+30", country: "Greece", flag: "🇬🇷", countryPt: "Grécia" },
  { code: "+351", country: "Portugal", flag: "🇵🇹", countryPt: "Portugal" },
  { code: "+55", country: "Brazil", flag: "🇧🇷", countryPt: "Brasil" },
  { code: "+244", country: "Angola", flag: "🇦🇴", countryPt: "Angola" },
  { code: "+258", country: "Mozambique", flag: "🇲🇿", countryPt: "Moçambique" },
  { code: "+238", country: "Cape Verde", flag: "🇨🇻", countryPt: "Cabo Verde" },
  { code: "+240", country: "Equatorial Guinea", flag: "🇬🇶", countryPt: "Guiné Equatorial" },
  { code: "+245", country: "Guinea-Bissau", flag: "🇬🇼", countryPt: "Guiné-Bissau" },
  { code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹", countryPt: "São Tomé e Príncipe" },
  { code: "+670", country: "East Timor", flag: "🇹🇱", countryPt: "Timor-Leste" },
  { code: "+853", country: "Macau", flag: "🇲🇴", countryPt: "Macau" },
  { code: "+86", country: "China", flag: "🇨🇳", countryPt: "China" },
  { code: "+91", country: "India", flag: "🇮🇳", countryPt: "Índia" },
  { code: "+81", country: "Japan", flag: "🇯🇵", countryPt: "Japão" },
  { code: "+82", country: "South Korea", flag: "🇰🇷", countryPt: "Coreia do Sul" },
  { code: "+61", country: "Australia", flag: "🇦🇺", countryPt: "Austrália" },
  { code: "+64", country: "New Zealand", flag: "🇳🇿", countryPt: "Nova Zelândia" },
  { code: "+7", country: "Russia", flag: "🇷🇺", countryPt: "Rússia" },
  { code: "+52", country: "Mexico", flag: "🇲🇽", countryPt: "México" },
  { code: "+54", country: "Argentina", flag: "🇦🇷", countryPt: "Argentina" },
  { code: "+56", country: "Chile", flag: "🇨🇱", countryPt: "Chile" },
  { code: "+57", country: "Colombia", flag: "🇨🇴", countryPt: "Colômbia" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪", countryPt: "Venezuela" },
  { code: "+51", country: "Peru", flag: "🇵🇪", countryPt: "Peru" },
  { code: "+27", country: "South Africa", flag: "🇿🇦", countryPt: "África do Sul" },
  { code: "+20", country: "Egypt", flag: "🇪🇬", countryPt: "Egito" },
  { code: "+212", country: "Morocco", flag: "🇲🇦", countryPt: "Marrocos" },
  { code: "+213", country: "Algeria", flag: "🇩🇿", countryPt: "Argélia" },
  { code: "+216", country: "Tunisia", flag: "🇹🇳", countryPt: "Tunísia" },
  { code: "+218", country: "Libya", flag: "🇱🇾", countryPt: "Líbia" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", countryPt: "Nigéria" },
  { code: "+254", country: "Kenya", flag: "🇰🇪", countryPt: "Quénia" },
  { code: "+971", country: "United Arab Emirates", flag: "🇦🇪", countryPt: "Emirados Árabes Unidos" },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", countryPt: "Arábia Saudita" },
  { code: "+972", country: "Israel", flag: "🇮🇱", countryPt: "Israel" },
  { code: "+90", country: "Turkey", flag: "🇹🇷", countryPt: "Turquia" },
  { code: "+48", country: "Poland", flag: "🇵🇱", countryPt: "Polónia" },
  { code: "+420", country: "Czech Republic", flag: "🇨🇿", countryPt: "República Checa" },
  { code: "+421", country: "Slovakia", flag: "🇸🇰", countryPt: "Eslováquia" },
  { code: "+36", country: "Hungary", flag: "🇭🇺", countryPt: "Hungria" },
  { code: "+40", country: "Romania", flag: "🇷🇴", countryPt: "Roménia" },
  { code: "+359", country: "Bulgaria", flag: "🇧🇬", countryPt: "Bulgária" },
  { code: "+385", country: "Croatia", flag: "🇭🇷", countryPt: "Croácia" },
  { code: "+386", country: "Slovenia", flag: "🇸🇮", countryPt: "Eslovénia" },
];
